import Vue from 'vue'

import {
  Vuetify,
  VApp,
  VAlert,
  VAvatar,
  VChip,
  VCheckbox,
  VCombobox,
  VDataTable,
  VDatePicker,
  VDialog,
  VDivider,
  VExpansionPanel,
  VNavigationDrawer,
  VFooter,
  VList,
  VBtn,
  VIcon,
  VImg,
  VGrid,
  VToolbar,
  VCard,
  VTooltip,
  VMenu,
  VForm,
  VSelect,
  VSubheader,
  VTextField,
  VTextarea,
  VProgressCircular,
  VProgressLinear,
  transitions
} from 'vuetify'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  components: {
    VApp,
    VAlert,
    VAvatar,
    VChip,
    VCheckbox,
    VCombobox,
    VDataTable,
    VDatePicker,
    VExpansionPanel,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VImg,
    VGrid,
    VToolbar,
    VCard,
    VTooltip,
    VDialog,
    VDivider,
    VForm,
    VTextField,
    VMenu,
    VSelect,
    VSubheader,
    VTextarea,
    VProgressCircular,
    VProgressLinear,
    transitions
  },
  theme: {
    primary: '#1C2260',
    secondary: '#424242',
    accent: '#82B1FF',
    error: '#FF5252',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FFC107'
  },
  iconfont: 'md'
})
