export const GET_ACCOUNT_BALANCE_REQUEST = 'GET_ACCOUNT_BALANCE_REQUEST'
export const GET_ACCOUNT_BALANCE_SUCCESS = 'GET_ACCOUNT_BALANCE_SUCCESS'
export const GET_ACCOUNT_BALANCE_ERROR = 'GET_ACCOUNT_BALANCE_ERROR'
