export const GET_TRANSACTIONS_HISTORY_REQUEST = 'GET_TRANSACTIONS_HISTORY_REQUEST'
export const GET_TRANSACTIONS_HISTORY_SUCCESS = 'GET_TRANSACTIONS_HISTORY_SUCCESS'
export const GET_TRANSACTIONS_HISTORY_ERROR = 'GET_TRANSACTIONS_HISTORY_ERROR'

export const COMMIT_TRANSACTION_REQUEST = 'COMMIT_TRANSACTION_REQUEST'
export const COMMIT_TRANSACTION_SUCCESS = 'COMMIT_TRANSACTION_SUCCESS'
export const COMMIT_TRANSACTION_ERROR = 'COMMIT_TRANSACTION_ERROR'

export const GET_TRANSACTION_REQUEST = 'GET_TRANSACTION_REQUEST'
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS'
export const GET_TRANSACTION_ERROR = 'GET_TRANSACTION_ERROR'
